Create ast iterator and optimize global variable access
titan-lang/titan-v0 pull request #185
Opened 2018-04-02 18:15 UTC by hugomg

2018-04-03 03:18 UTC, gligneul requested changes
Minor stuff

2018-04-03 03:18 UTC, gligneul commented on spec/global_upvalues_spec.lua
> +
s/\n//

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/ast_iterator.lua
> +
s/\n//

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/ast_iterator.lua
> +    if     tag == ast.Exp.Nil then
We should either have the `-- Nothing to do` in the same line here like the `Type` method.

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/scope_analysis.lua
> +
s/\n//

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/scope_analysis.lua
> +        ast_iterator.default.Type(self, type_node, st, errors)
Why not use the `:` notation here?

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/global_upvalues.lua
> +
s/\n//

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/global_upvalues.lua
> +
s/\n//

2018-04-03 03:18 UTC, gligneul commented on titan-compiler/global_upvalues.lua
> +
s/\n//

2018-04-03 03:18 UTC, gligneul commented on spec/global_upvalues_spec.lua
> +
s/\n//

2018-04-03 15:03 UTC, hugomg commented on titan-compiler/scope_analysis.lua
> +        ast_iterator.default.Type(self, type_node, st, errors)
Because we need to explicitly pass the `self`

2018-04-04 00:33 UTC, gligneul approved these changes

2018-04-04 00:33 UTC, merged